### PR TITLE
enforce known language codes

### PR DESCRIPTION
**Pull request by manno**

### CODE REVIEW

**Comment by a-tze** [comment]
This is incosinstent. Our beloved schwitzerdütsch does not exist in 2-letter language codes, as you can see with your check against gsw :-(

**Comment by manno** [comment]
I'm not checking against the number of letters. I'm checking against a white list.
How did I come up with that list? 

Recordings:
```ruby
{
"en"=>8492,
"de-en-gsw"=>4,
"eng-deu-fra"=>3,
"de"=>414,
"deu-eng"=>3,
"deu"=>6,
"en-de"=>415,
"de-en"=>80
}
```
Now I can just fix these 12 recordings and all codes are consistent. (Note 'en' is probably the default for old talks.)

**Comment by a-tze** [comment]
Yes, and in the whitelist is "gsw". If you fix the recordings you will still need to keep gsw, so it will be a mix of 2 and 3 letter codes. If it doesn't matter that the semantic of the field is completely broken, then allright.

Actually the other talks should be fixed. But then it is inconsistent (but on a less severe level) with the filenames/slugs.

And everything because of schwitzerdütsch, yeah.

**Comment by manno** [comment]
I'd prefer to keep the pre-existing ISO 639-1 codes, falling back to ISO 639-2 if no 639-1 code is available.

**Comment by a-tze** [comment]
ok, so future releases with 2-letter-codes, if possible? 

e.g. `en-de-gsw` ?

**Comment by manno** [comment]
I see, so this would be a chance to introduce consistent codes across the whole process?
So we'd keep -1/-2 in the file names and only use -2 codes in the scripts/api?

**Comment by a-tze** [comment]
Yes, this is the chance to get rid of mapping, because at encoding level the -2 codes are needed. 

If nothing breaks, keeping the current mixed filenames and using only -2 codes in the future (metadata AND filenames!) would be my preferred solution.

**Pull request merged**
